import { NextPage } from "next";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import Head from "next/head";
import Header from "~/components/Header";
import Analytics from "~/features/analytics";
import { useEffect } from "react";
import Tasks from "~/features/tasks";

async function notificationPermission() {
  const permission = await Notification.requestPermission();
  if (permission === "granted") {
    console.log("Notification permission granted.");
  } else {
    console.log("Unable to get permission to notify.");
  }
}

const Home: NextPage = () => {
  useEffect(() => {
    void notificationPermission();
  }, []);

  return (
    <>
      <Head>
        <title>Tasks App - Lief Assignment</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gray-100">
        <div className="max-w-screen-lg mx-auto px-4 sm:px-6 lg:px-8">
          <Header />

          <div className="bg-white rounded-lg shadow-lg mt-8">
            <Tabs defaultValue="tasks" className="border-b">
              <TabsList className="flex justify-between">
                <TabsTrigger
                  className="py-4 px-6 font-medium text-gray-600 hover:text-gray-900"
                  value="tasks"
                >
                  Tasks
                </TabsTrigger>
                <TabsTrigger
                  className="py-4 px-6 font-medium text-gray-600 hover:text-gray-900"
                  value="analytics"
                >
                  Analytics
                </TabsTrigger>
              </TabsList>
              <div className="p-6">
                <TabsContent value="tasks">
                  <Tasks />
                </TabsContent>
                <TabsContent value="analytics">
                  <Analytics />
                </TabsContent>
              </div>
            </Tabs>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
